In [0]:
import numpy as np


In [0]:
a=np.zeros([2,2])

In [0]:
b=np.ones([2,2])


In [0]:
np.add(a,b)

array([[1., 1.],
       [1., 1.]])

In [0]:
np.multiply(a,b)

array([[0., 0.],
       [0., 0.]])

In [0]:
np.dot(a,b)

array([[0., 0.],
       [0., 0.]])

In [0]:
np.matmul(a,b)

array([[0., 0.],
       [0., 0.]])

find difference between matmul and dot multiply


In [0]:
n=np.random.randn(10,10)

In [0]:
n

array([[-3.31624518e-01,  2.81679202e+00,  1.94510959e+00,
         1.81059940e+00, -1.72088856e+00, -7.15806150e-01,
        -8.35521987e-01, -1.11866992e+00,  4.76676217e-01,
        -6.61159893e-01],
       [ 1.25762953e+00, -1.30923239e-01,  3.31816372e-02,
        -1.30210870e+00,  1.36722266e-01, -2.13601824e+00,
        -7.73135355e-01,  1.19349753e-01, -1.48513432e+00,
         8.64827853e-01],
       [-8.42299521e-01, -5.10124870e-01,  1.05619501e+00,
         5.24354447e-01,  5.19466201e-01, -1.25447675e+00,
         1.74857820e-02, -6.70167957e-01,  4.41870961e-01,
        -3.78552589e-01],
       [ 2.57752287e-01,  1.50614142e+00, -1.64876411e+00,
         8.01870900e-01,  2.11249210e-01,  8.46444245e-01,
        -4.80392897e-01, -9.91595613e-01, -4.58506484e-01,
        -2.57386372e-01],
       [ 4.78096963e-01, -2.17805921e-01, -2.06915904e-01,
        -1.87851536e-01, -6.02182027e-01,  1.21606315e+00,
         1.32591690e-01,  8.40812671e-01,  3.80549864e-02,
         8.

In [0]:
m=np.random.randn(10,1)

In [0]:
m

array([[ 0.3822016 ],
       [ 0.34933768],
       [-0.3946766 ],
       [-1.17517597],
       [-0.97299122],
       [ 1.49646946],
       [ 0.82189948],
       [-0.55986271],
       [-0.50002795],
       [ 0.50534721]])

In [0]:
m.shape,n.shape

((10, 1), (10, 10))

In [0]:
s = np.multiply(m,n)
s,s.shape

(array([[-1.26747423e-01,  1.07658243e+00,  7.43424004e-01,
          6.92013996e-01, -6.57726367e-01, -2.73582258e-01,
         -3.19337843e-01, -4.27557436e-01,  1.82186414e-01,
         -2.52696371e-01],
        [ 4.39337379e-01, -4.57364203e-02,  1.15915960e-02,
         -4.54875627e-01,  4.77622388e-02, -7.46191648e-01,
         -2.70085309e-01,  4.16933656e-02, -5.18813372e-01,
          3.02116953e-01],
        [ 3.32435910e-01,  2.01334349e-01, -4.16855453e-01,
         -2.06950430e-01, -2.05021154e-01,  4.95112616e-01,
         -6.90122898e-03,  2.64499610e-01, -1.74396128e-01,
          1.49405848e-01],
        [-3.02904294e-01, -1.76998120e+00,  1.93758797e+00,
         -9.42339412e-01, -2.48254995e-01, -9.94720936e-01,
          5.64546188e-01,  1.16529934e+00,  5.38825802e-01,
          3.02474280e-01],
        [-4.65184148e-01,  2.11923249e-01,  2.01327358e-01,
          1.82777895e-01,  5.85917826e-01, -1.18321877e+00,
         -1.29010550e-01, -8.18103347e-01, -3.702716

In [0]:
f = np.dot(n,m)
f.shape

(10, 1)

In [0]:
f = np.dot(m,n)
f.shape

ValueError: shapes (10,1) and (10,10) not aligned: 1 (dim 1) != 10 (dim 0)

In [0]:
f = np.matmul(m,n)
f.shape

ValueError: shapes (10,1) and (10,10) not aligned: 1 (dim 1) != 10 (dim 0)

In [0]:
f = np.matmul(n,m)
f,f.shape

(array([[-2.06785082],
        [-0.90008519],
        [-3.93859517],
        [ 1.65370812],
        [ 2.86325654],
        [ 3.77359199],
        [ 1.76122254],
        [ 4.02057214],
        [-0.24372968],
        [ 2.23089828]]), (10, 1))

In [0]:
m=np.random.randn(10)

In [0]:
m,m.shape

(array([-0.09649918,  2.25235253,  1.19713507, -0.39983193, -0.75044478,
        -1.23662454, -0.68081023,  1.02435108,  0.81584545, -0.25768081]),
 (10,))

In [0]:
n=np.random.randn(10)
n,n.shape

(array([ 1.28534477, -0.2874923 , -0.20905756,  0.68716119,  0.28250232,
         1.08146923,  1.12420758,  0.77187411,  0.43248163,  0.08872952]),
 (10,))

In [0]:
f =np.dot(m,n)

In [0]:
f,f.shape

(-2.4906892930014672, ())

In [0]:
f =np.matmul(m,n)

In [0]:
f,f.shape

(-2.4906892930014672, ())

In [0]:
f =np.matmul(n,m)

In [0]:
f,f.shape

(-2.4906892930014672, ())

In [0]:
m=np.random.randn(10,1)
n=np.random.randn(10)

In [0]:
f1 = np.dot(n,m)
f2 =np.matmul(n,m)
f1.shape, f2.shape

((1,), (1,))

In [0]:
f1

array([-0.05349772])

In [0]:
f2

array([-0.05349772])

In [0]:
f2 =np.dot(n,10)

In [0]:
import numpy as np
from io import StringIO
data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)


array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [0]:
# import  numpy as np
# a=np.array([1,2,3])
# b=np.array([(1,2,3,4),(7,8,9,10)],dtype=int)
# print(a)
# print(b)

"""Initial placeholder"""
# import numpy as np
# import random
# print(" 1  dimensional array\n",np.zeros(3))  
# print("2d array of all zeros\n",np.zeros((2,3)))  
# print("3d array of all zero\n",np.zeros((3,2,4)))
# print("3*4 array with all value2\n",np.full((3,4),2))
# print("3*5 array of randomfloats between 0-1\n",np.random.rand(3,5))
# print("3*4 array with all values 1\n",np.ones((3,4)))
# print("4*4 array of 0 with 1 on diagonal\n",np.eye(4))


'''saving'''
# import numpy as np
# a = np.arange(5)
# print("a is: ")
# print(a)
# np.save('geekfile',a)


'''Loading'''
# import numpy as np 
# b= np.load('geekfile.npy')
# print("b is: ")
# print(b)

'''text/csv file'''
# import numpy as np
# from io import StringIO
# print("---load text---")
# x=StringIO("0 1 2 \n3 4 5")
# y =np.loadtxt(x)
# print(y)

# print("---gen from txt---")
# data =u"1,2,3,\n4,5,6"
# b = np.genfromtxt(StringIO(data),delimiter=",")
# print("gen from txt",b)


# print("---savetxt---")
# x = np.arange(0,10,1)
# c = np.savetxt('testfile.txt',x,delimiter=' ')
# a = open("testfile.txt",'r')
# print("the file contains: ")
# print(a.read())


'''properties'''
# import numpy as np
# a= np.array([[1,2,3]])
# print(a.size)
# print(a.shape)
# print(a.dtype)
# print(a)
# print(np.copy(a))
# print(a.view)



'''Sorting'''
# import numpy as np
# a= np.array([[15,54,4,5,2,485],[10,55,31,1,44,32]])
# print(np.sort(a))
# print(np.sort(a,axis=1))
# b = np.array([[1,2],[3,4],[5,6]])  
# print(b.reshape(2,3))


'''adding'''
# import numpy as np
# a = np.array([[1,2,3],[4,5,6]])
# print(np.append(a,7))
# print(np.insert(a,4,8))


'''Removing'''
# import numpy as np
# a= np.array([1,2,3,4,5])
# print(np.delete(a,2,axis=0))
# print(np.delete(a,3,axis=0))


'''combining'''
# import numpy as np
# a = np.array([1,2,3,4,5]) 
# b = np.array([6,7,8,9,10])
# print(np.concatenate((a,b),axis = 0))
# print(np.concatenate((b,a),axis = 0))



'''split'''
# import numpy as np
# a = np.array([1,2,3,4,5,6])
# print(np.split(a,3))


'''indexing'''
# import numpy as np
# a = np.array([[1,1],[2,2],[3,3] ])
# a[0]=7
# a[1,0]=1
# print(a)


'''subseting'''
# import numpy as np
# a = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
# b = np.array([1,2,3,4]) 
# print(b[2])
# print(a[2,4])


'''slicing'''
# import numpy as np
# a = np.array([[1,2,3,4,5],[10,11,12,13,14],[15,16,17,18,19]])
# b = np.array([1,2,3,4,5,6]) 
# print(b[0:4])
# print(a[0:2,4])
# print(b[:2])
# print("abc: ",a[:,4])



'''maths'''
# import numpy as np
# a = 400
# b = 40
# print("add",np.add(a,b))
# print("subtract",np.subtract(a,b))
# print("multiply",np.multiply(a,b))
# print("division",np.divide(a,b))
# print("exponentiation",np.exp(a))
# print("Square root",np.sqrt(b))
# print("comparision",a==b)

# w = np.array([1,2,3,4,5,6])
# x= np.array([1,2,3,4,5,6])
# print("array wise compare",np.array_equal(w,x))


'''functions'''
import numpy as np
a = np.array([20,2,1,34])
print("array wise sum",a.sum())
print("array wise min value: ",a.min())
print("array wise max value: ",a.max(axis=0))
print("Mean", a.mean())
print("Median",np.median(a))